# Generated by Django 4.2.5 on 2023-10-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homepage", "0002_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="product_images/"),
        ),
    ]
