# Generated by Django 4.2.5 on 2023-10-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homepage", "0003_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                default="default_image.jpg",
                null=True,
                upload_to="product_images/",
            ),
        ),
    ]
