# Generated by Django 4.2.5 on 2023-10-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homepage", "0009_basketitem_shoppingcart_basketitem_basket_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("Action", "Action"),
                    ("Adventure", "Adventure"),
                    ("Role-Playing", "Role-Playing"),
                    ("Simulation", "Simulation"),
                    ("Strategy", "Strategy"),
                    ("Sports", "Sports"),
                    ("Puzzle", "Puzzle"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=20,
            ),
        ),
    ]
